self.addEventListener('install', (event) => {
  // Activate quickly for demo purposes
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // This “virtual” resource is generated by the SW, so we always have something to cache.
  if (url.pathname.endsWith('/probe-resource.txt')) {
    const body = `probe ok @ ${new Date().toISOString()}\n`;
    event.respondWith(
      new Response(body, { headers: { 'content-type': 'text/plain; charset=utf-8' } })
    );
    return;
  }

  // Otherwise, do nothing special.
});
